### ISSUE TITLE
 Syntax error or access violation: 1064

### ISSUE THREAD

**Issue by Silverteal** [kilowhat/flarum-ext-audit-free#2]
Error happens while enabling this extension
PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json null, `created_at` datetime not null) default character set utf8mb4 collate' at line 1 in ***\flarum\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOConnection.php:79

**Comment by clarkwinkelmann** [comment]
Your database server probably doesn't meet the requirements https://kilowhat.net/flarum/extensions/audit#requirements

MariaDB 10.2.7+ is required.
